### ISSUE TITLE
npm install passport-userapp returns 404

### ISSUE THREAD

**Issue by scottcorgan** [userapp-io/passport-userapp#4]
npm is saying your module cannot be found. Is it just me?

```
 >  npm install passport-userapp
npm WARN package.json column@0.0.0 No description
npm WARN package.json column@0.0.0 No repository field.
npm WARN package.json column@0.0.0 No README data
npm http GET https://registry.npmjs.org/passport-userapp
npm http 304 https://registry.npmjs.org/passport-userapp
npm http GET https://registry.npmjs.org/passport-userapp/-/passport-userapp-1.1.0.tgz
npm http 404 https://registry.npmjs.org/passport-userapp/-/passport-userapp-1.1.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/passport-userapp/-/passport-userapp-1.1.0.tgz
npm ERR! Error: 404 Not Found
npm ERR!     at WriteStream.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/fetch.js:57:12)
npm ERR!     at WriteStream.EventEmitter.emit (events.js:117:20)
npm ERR!     at fs.js:1598:14
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:105:5
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 13.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "passport-userapp"
npm ERR! cwd /Users/scott/www/column3
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.4
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/scott/www/column3/npm-debug.log
npm ERR! not ok code 0
```

**Comment by timothyej** [comment]
No, we've had issues with npm before. It could be related to your version, or your region. I would recommend you to download the source and install with "npm install" instead. How does that sound?

**Comment by beda** [comment]
I have the same issue Error: 404 Not Found

**Comment by beda** [comment]
Ok. Changing registry did the trick:

```
npm --registry http://registry.npmjs.eu/ install passport-userapp --save 
```

**Comment by scottcorgan** [comment]
Any way we can get this on all the registries?

On Tue, Apr 8, 2014 at 6:01 AM, Beda Steinacher notifications@github.comwrote:

> Ok. Changing registry did the trick:
> 
> npm --registry http://registry.npmjs.eu/ install passport-userapp --save
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/userapp-io/passport-userapp/issues/4#issuecomment-39830833
> .

## 
- Scott

**Comment by timothyej** [comment]
Thanks for the help! I will do some research and contact npm if I can't find a solution to this problem.

**Comment by beda** [comment]
there still seems to be a problem. the version it installed does not correspond to the current master. i had to manually copy the content. otherwise token is missing from user object.

**Comment by timothyej** [comment]
I think there is a problem with the npm repository. I will contact npm about it and see if there's something they can do. Another way to install it is to download the source and then run "$ npm install -g" in that folder.

**Comment by timothyej** [comment]
I've now tried to unpublish the whole package and then republished it again as version 1.1.1. Could anyone verify that it works? Thanks!

**Comment by beda** [comment]
It does work for me. Thanks!
